---
driver:
  name: vagrant
  vm_hostname: 'owncloud.local'
  network:
  - ["forwarded_port", {guest: 80, host: 8080, auto_correct: true}]
  - ["forwarded_port", {guest: 443, host: 8443, auto_correct: true}]
  customize:
    memory: 512

provisioner:
  name: chef_solo
  require_chef_omnibus: true
  attributes:
    owncloud:
      config:
        trusted_domains:
          - "localhost:8080"
          - "localhost:8443"

platforms:
- name: ubuntu-12.04
- name: ubuntu-10.04
- name: centos-6.5
- name: centos-5.10
- name: debian-7.2.0
- name: ubuntu-13.10

suites:
- name: mysql
  run_list: ["recipe[owncloud_test::mysql]"]
- name: postgresql
  run_list: ["recipe[owncloud_test::postgresql]"]
- name: sqlite
  run_list: ["recipe[owncloud_test::sqlite]"]
- name: nginx
  run_list: ["recipe[owncloud_test::nginx]"]
- name: ssl_data_bag
  run_list: ["recipe[owncloud_test::mysql]"]
  data_bags_path: "test/integration/mysql/data_bags"
  encrypted_data_bag_secret_key_path: "test/integration/mysql/encrypted_data_bag_secret"
  attributes:
    owncloud:
      ssl_key:
        source: data-bag
        bag: ssl
        item: key
        item_key: content
        encrypted: true
      ssl_cert:
        source: data-bag
        bag: ssl
        item: cert
        item_key: content
- name: ssl_attribute
  run_list: ["recipe[owncloud_test::mysql]"]
  attributes:
    owncloud:
      ssl_key:
        source: attribute
        content: |
          -----BEGIN PRIVATE KEY-----
          MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAOgkYt9sTZb/mEwG
          zNFIOkOrNhtSKyst300Ycdjg/8C1+Ji43SapBZeQpYuymOE0bCa7No0tktvYgxLn
          vXxHnW5yJfWbskX9ADAa8LxftyRUiASta9SXoDRF4Usayb1+84TUsDLjP02IjVtc
          EiwxnhIp4X8C0jyKopCVP1wc4SwJAgMBAAECgYEAtfw4arCrzvFGwmseS/7UdlIV
          U6vB3dLTWMwODBivRrMhVRCvhmxAzwX9UZvMT9hZ5K8lX93XYHPGpZ54pKI73mhT
          rkzIWc49J71Yeucli/IdCUj6ZjU6wz7M8S6Iq5PAPet0B43Tgr2GuSpYBTaCGDKs
          zPNhUiU/aya0zVnAZxECQQD6Ds7GxFn/way0nrdjOl93daEKg9qKNNcxQc9edO81
          4ZQFoB5PGD0FAaSqFfei7kNG4Ab1TkvGKnNLNg1J7ehdAkEA7aiXPGDle9jCmUSm
          Qrej2Cs7OJNIm5K3FiqtXyd0/zszHbsp9eT1z5xIbRZhzF85I/xxda3O4brvuJq3
          BqmnnQJBAKHgmCfA0OpqvJ0o6ltIXKj+80PVW9KAppZyngXt+TWOVL7Xiwd1D3uA
          NtMM6YUGbXMicB65kwA0VvLniO7FHtkCQGJg7KHw1m4q73s0wMJTdH6SfsRPq7nC
          xQlnBzehhLv2zJUdGiSQ7/ROFGkb38YTEPtFj84P8djdYkh/uw4GAr0CQA1BCV5C
          mCRO24Sn5K9AtA4Cu1NsAM8/sfBvewJ8MjkxCG/lnWjSDNMoVXivo5kk5txT4uVF
          1pdo84Vs2Abj3JE=
          -----END PRIVATE KEY-----
      ssl_cert:
        source: attribute
        content: |
          -----BEGIN CERTIFICATE-----
          MIICjDCCAfWgAwIBAgIJALJSpKd0ZsHVMA0GCSqGSIb3DQEBBQUAMF4xCzAJBgNV
          BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
          aWRnaXRzIFB0eSBMdGQxFzAVBgNVBAMMDm93bmNsb3VkLmxvY2FsMCAXDTE0MDIx
          MzE3MzYyMFoYDzIxMTQwMTIwMTczNjIwWjBeMQswCQYDVQQGEwJBVTETMBEGA1UE
          CAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRk
          MRcwFQYDVQQDDA5vd25jbG91ZC5sb2NhbDCBnzANBgkqhkiG9w0BAQEFAAOBjQAw
          gYkCgYEA6CRi32xNlv+YTAbM0Ug6Q6s2G1IrKy3fTRhx2OD/wLX4mLjdJqkFl5Cl
          i7KY4TRsJrs2jS2S29iDEue9fEedbnIl9ZuyRf0AMBrwvF+3JFSIBK1r1JegNEXh
          SxrJvX7zhNSwMuM/TYiNW1wSLDGeEinhfwLSPIqikJU/XBzhLAkCAwEAAaNQME4w
          HQYDVR0OBBYEFH+LWAqDxMpEObxsdPR/HUxbSvTaMB8GA1UdIwQYMBaAFH+LWAqD
          xMpEObxsdPR/HUxbSvTaMAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADgYEA
          AHeOpZbU6ak47dHfZVevB34JUkuje+nnG01ahDqtRtIuAiXdWE8+r4XeNeQTMQMZ
          0/WOwseFPzfG3D9KaynYe7Py7kaACHZweEyVDgRlgxa7U2fJim+/f6pEcRUIfb2F
          wCVUQVe2b2XgEGlbTpmzyOHrERKM2C7w0ueeOG/FU04=
          -----END CERTIFICATE-----
